export enum SubCategory {
  LAPTOPS = 1,
  SMARTPHONES = 2,
  HOME_APPLIANCES = 3,
  T_SHIRTS = 4,
  JEANS = 5,
  SHOES = 6,
  CONSTRUCTORS = 7,
  BOARD_GAMES = 8,
  CAMPING_HIKING = 9,
  FITNESS = 10,
  MAKEUP = 11,
  FRAGRANCE = 12,
  HAIR = 13
}
